version: '3'

services:

  database:
    image: postgres:9.6-alpine
    container_name: atlassian-database
    restart: always
    volumes:
      - /srv/atlassian/database:/var/lib/postgresql/data

  backup:
    build: backup
    container_name: atlassian-backup
    restart: always
    links:
      - database
    volumes:
      - /srv/atlassian/db-backup:/root/backup

  jira:
    build: jira
    container_name: atlassian-jira
    restart: always
    links:
      - database
    ports:
      - "8080:8080" 
    volumes:
      - /srv/atlassian/jira:/var/atlassian/jira
    env_file:
      - jira.env

  confluence:
    build: confluence
    container_name: atlassian-confluence
    restart: always
    links:
      - database
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - /srv/atlassian/confluence:/var/atlassian/confluence
    env_file:
      - confluence.env

  bitbucket:
    build: bitbucket
    container_name: atlassian-bitbucket
    restart: always
    links:
      - database
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - /srv/atlassian/bitbucket:/var/atlassian/bitbucket
    env_file:
      - bitbucket.env
