version: '3'

services:

  database:
    build: database
    container_name: atlassian-database
    restart: always
    volumes:
      - /srv/atlassian/database:/var/lib/postgresql/data
      - /srv/atlassian/db-backup:/root/backup

  jira:
    build: jira
    container_name: atlassian-jira
    restart: always
    links:
      - database
    ports:
      - "8080:8080" 
    volumes:
      - /srv/atlassian/jira:/var/atlassian/jira
    env_file:
      - jira.env

  confluence:
    build: confluence
    container_name: atlassian-confluence
    restart: always
    links:
      - database
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - /srv/atlassian/confluence:/var/atlassian/confluence
    env_file:
      - confluence.env

