#!/bin/sh

mkdir -p /root/backup
cd /root/backup

rm -f *.sql
pg_dumpall --globals-only -h database -U postgres -f globals-only.sql
CMD="SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres';"
psql -qtA -h database -U postgres -c "${CMD}" | xargs -I DB pg_dump -h database -U postgres -f DB.sql DB

git init .
git config user.email "git-postgres-backup@nowhere"
git config user.name "Git Postgres Backup"
git config pager.log cat
git add -A .
git commit -m "${1:-update}"

rm -f *.sql

