#!/bin/bash

cd /root/backup

if [ -z "$2" ]; then
  echo
  echo "usage: restore <database> <commit hash>"
  echo
  LESS="--no-init" git log --pretty=format:"%h, %cr: %s" -n 10
  echo
  exit 1
fi

set -e -x
pg_dump -h database -U postgres -f ${1}.bak ${1}
git checkout "${2}" -- ${1}.sql
dropdb -h database -U postgres ${1}
createdb -e -h database -U postgres -E UNICODE -l C -T template0 -O ${1} ${1}
psql -q -1 -h database -U postgres ${1} < ${1}.sql
mv ${1}.bak ${1}.sql

